#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:10:00
#SBATCH --mem=10G

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report

singularity exec docker://brainlife/mne:1.2.1 python3 main.py
