#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#SBATCH --mem=8G

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report

singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
